// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_RV12TUsVbj3UWMoVr9HCmRK0oMMIAk',
    appId: '1:1011373144650:web:0893b566a1d2bd360184b3',
    messagingSenderId: '1011373144650',
    projectId: 'untitled-9d276',
    authDomain: 'untitled-9d276.firebaseapp.com',
    storageBucket: 'untitled-9d276.appspot.com',
    measurementId: 'G-543NMD4VQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyozWd029WqNToIR57U_aE31pnhbKVz3w',
    appId: '1:1011373144650:android:8e70ee9603819a450184b3',
    messagingSenderId: '1011373144650',
    projectId: 'untitled-9d276',
    storageBucket: 'untitled-9d276.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAndtMs8tt9m1wYO65oOiYsC6Uw-rYopwo',
    appId: '1:1011373144650:ios:a7b2220a4cebc3890184b3',
    messagingSenderId: '1011373144650',
    projectId: 'untitled-9d276',
    storageBucket: 'untitled-9d276.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAndtMs8tt9m1wYO65oOiYsC6Uw-rYopwo',
    appId: '1:1011373144650:ios:a7b2220a4cebc3890184b3',
    messagingSenderId: '1011373144650',
    projectId: 'untitled-9d276',
    storageBucket: 'untitled-9d276.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY_RV12TUsVbj3UWMoVr9HCmRK0oMMIAk',
    appId: '1:1011373144650:web:4b903aa07c1b533c0184b3',
    messagingSenderId: '1011373144650',
    projectId: 'untitled-9d276',
    authDomain: 'untitled-9d276.firebaseapp.com',
    storageBucket: 'untitled-9d276.appspot.com',
    measurementId: 'G-ZCBHBGKLJ7',
  );
}
